# Generated by Django 3.2.7 on 2021-10-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_market',
            field=models.BooleanField(default=True),
        ),
    ]
