# Generated by Django 3.2.7 on 2021-10-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_is_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_market',
            field=models.BooleanField(default=False),
        ),
    ]
