# Generated by Django 3.2.7 on 2021-12-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='watch_count',
            field=models.IntegerField(default=0, verbose_name='Watch Count'),
        ),
    ]
