# Generated by Django 3.2.7 on 2021-11-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_box_category',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Box Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_long_box_category',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Long Box Category'),
        ),
    ]
