# Generated by Django 3.2.7 on 2021-11-11 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marka_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='marka_product', to='main.marka', verbose_name='User'),
            preserve_default=False,
        ),
    ]
