# Generated by Django 3.2.7 on 2021-10-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Category Order'),
        ),
    ]
