# Generated by Django 3.2.7 on 2021-12-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211202_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_az',
            field=models.CharField(max_length=120, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_az',
            field=models.CharField(max_length=120, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Title'),
        ),
    ]
