# Generated by Django 3.2.7 on 2021-12-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='Is Vip'),
        ),
    ]
