# Generated by Django 3.2.7 on 2021-10-10 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Basligi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='marka_image', verbose_name='Image')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Markalar',
            },
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marka_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_marka', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Arzu Listi',
                'verbose_name_plural': 'Arzu Listleri',
            },
        ),
        migrations.CreateModel(
            name='Modell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Basligi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='model_image', verbose_name='Image')),
                ('min_year', models.IntegerField(blank=True, null=True, verbose_name='Minimal Buraxilis ili')),
                ('max_year', models.IntegerField(blank=True, null=True, verbose_name='Maksimal buraxilis ili')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marka_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marka_model', to='main.marka', verbose_name='Marka')),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Markalar',
            },
        ),
    ]
