# Generated by Django 3.2.7 on 2021-11-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='model_id',
            new_name='product_id',
        ),
    ]
