# Generated by Django 3.2.7 on 2021-12-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertisement_image', verbose_name='Image')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_top', models.BooleanField(default=False, verbose_name='Top Advertisement')),
                ('is_bottom', models.BooleanField(default=False, verbose_name='Bottom Adverstiment')),
                ('is_right', models.BooleanField(default=False, verbose_name='Right Advertisement')),
                ('is_left', models.BooleanField(default=False, verbose_name='Left Advertisement')),
            ],
            options={
                'verbose_name': 'Reklam Banneri',
                'verbose_name_plural': 'Reklam Bannerleri',
            },
        ),
    ]
