# Generated by Django 3.2.7 on 2021-12-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marka',
            name='title_az',
            field=models.CharField(max_length=120, null=True, verbose_name='Basligi'),
        ),
        migrations.AddField(
            model_name='marka',
            name='title_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Basligi'),
        ),
        migrations.AddField(
            model_name='marka',
            name='title_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Basligi'),
        ),
        migrations.AddField(
            model_name='modell',
            name='title_az',
            field=models.CharField(max_length=120, null=True, verbose_name='Basligi'),
        ),
        migrations.AddField(
            model_name='modell',
            name='title_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Basligi'),
        ),
        migrations.AddField(
            model_name='modell',
            name='title_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Basligi'),
        ),
    ]
