# Generated by Django 3.2.7 on 2021-11-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_model_id_wishlist_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
