# Generated by Django 3.2.7 on 2021-12-18 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_advertisements_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisements',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
