# Generated by Django 3.2.7 on 2021-12-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211218_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='image',
            field=models.ImageField(default=1, upload_to='advertisement_image', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
