# Generated by Django 3.2.7 on 2021-12-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_advertisements_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='image',
            field=models.ImageField(upload_to='advertisement_image/', verbose_name='Image'),
        ),
    ]
