# Generated by Django 3.2.7 on 2021-12-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_advertisements_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Reklamin adi'),
        ),
    ]
